/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eventos;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import eventos.entity.Falecimento;
import eventos.entity.Realocação;
import eventos.entity.ProvimentoCargo;
import eventos.entity.Setor;
import eventos.entity.Vinculo;

public class App {

    public static void main(String[] args) {
        List<String> eventos = new ArrayList<>();
        List<Vinculo> vinculos = new ArrayList<>();
        vinculos.add(new Vinculo(1L, Setor.SETOR_A));

        ProvimentoCargo pc = new ProvimentoCargo();
        pc.proverCargo(vinculos, 1L, new Vinculo(2L, Setor.SETOR_A));

        System.out.println("\n----------------");
        vinculos.forEach(System.out::println);

        Realocação f = new Realocação();
        f.realocar(vinculos, 1L, 2L, Setor.SETOR_C);

        System.out.println("\n----------------");
        vinculos.forEach(System.out::println);

        Falecimento fal = new Falecimento();
        fal.registrarFalecimento(vinculos, 2L);

        System.out.println("\n----------------");
        vinculos.forEach(System.out::println);
    }
}
