/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package time.and.date;

import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Calendar;

public class App {

    public static void main(String[] args) throws ParseException {
        
        // current Date
        Date now = new Date(System.currentTimeMillis());
        System.out.println(now);
        
        // Data formater
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
        Date date1 = sd.parse("19/08/2023");
        System.out.println(date1);
        
        // instanciando Date a partir de uma data no format iSO 8601
        Date y = Date.from(Instant.parse("2023-08-19T19:07:00Z"));
        System.out.println(y);

        // Calender and set Date
        Calendar cal = Calendar.getInstance();
        cal.setTime(y);

        // extract minutes from Date
        int minutes = cal.get(Calendar.MINUTE);
        System.out.println(minutes);

        // extract year from Date
        int year = cal.get(Calendar.YEAR);
        System.out.println(year);

        // extract month from Dtae
        int month = cal.get(Calendar.MONTH) + 1;
        System.out.println(month);

        // add time to Date
        cal.add(Calendar.HOUR, 5);
        System.out.println(cal.getTime());
    }
}
