/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistema.de.enfileiramento;

import sistema.de.enfileiramento.entity.Player;
import sistema.de.enfileiramento.enums.Position;
import sistema.de.enfileiramento.service.PlayerService;
import sistema.de.enfileiramento.service.TeamService;

public class App {
    public static void main(String[] args) throws InterruptedException {

        PlayerService playerService = new PlayerService();
        TeamService teamService = new TeamService();

        Player p1 = new Player("1001");
        Player p2 = new Player("1002");
        Player p3 = new Player("1003");
        Player p4 = new Player("1004");
        Player p5 = new Player("1005");
        Player p6 = new Player("1006");
        Player p7 = new Player("1007");
        Player p8 = new Player("1008");
        Player p9 = new Player("1009");
        Player p10 = new Player("1010");
        Player p11 = new Player("1011");
        Player p12 = new Player("1012");
        Player p13 = new Player("1013");
        Player p14 = new Player("1014");
        Player p15 = new Player("1015");
        Player p16 = new Player("1016");
        Player p17 = new Player("1017");
        Player p18 = new Player("1018");

        Thread teamsThread = new Thread(new TeamServer(playerService));
        teamsThread.start();

        Thread matcThread = new Thread(new MatchServer(teamService));
        matcThread.start();

        Thread.sleep(2000);

        playerService.enterQueue(p1);
        p2.changePositionPermutation(Position.WARRIOR, Position.ARCHER, Position.MAGE);
        p2.setHasPreference(1.0);
        playerService.enterQueue(p2);
        playerService.enterQueue(p3);
        playerService.enterQueue(p4);
        playerService.enterQueue(p5);
        playerService.enterQueue(p6);

        playerService.enterQueue(p7);
        playerService.enterQueue(p8);

        Thread.sleep(3000);

        playerService.enterQueue(p9);
        playerService.enterQueue(p10);
        playerService.enterQueue(p11);

        playerService.enterQueue(p12);

        Thread.sleep(5000);

        playerService.enterQueue(p13);
        playerService.enterQueue(p14);
        playerService.enterQueue(p15);
        playerService.enterQueue(p16);
        playerService.enterQueue(p17);
        playerService.enterQueue(p18);
    }
}
