/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mapa;

import java.util.HashMap;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        
        Map<Integer, String> capitais = new HashMap<>();
        
        capitais.put(1, "Natal");
        capitais.put(2, "João Pessoa");
        capitais.put(3, "Pernambuco");

        for(HashMap.Entry<Integer, String> capital : capitais.entrySet()) {
            System.out.printf("%d-%s%n", capital.getKey(), capital.getValue());
        }
    }
}
