/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prova.pratica;

import prova.pratica.numeroMaximo.NumeroMaximo;
import prova.pratica.palindromo.Palindromo;

public class App {

    public static void main(String[] args) {

        // NumeroMaximo nm = new NumeroMaximo();

        // int[] lista = {1,2,3,4,5};

        // System.out.println(nm.numeroMaximo(lista));

        Palindromo pl = new Palindromo();

        System.out.println(pl.ehPalindromo("Amor a Roma"));
    }
}
