/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package funcionarios;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import funcionarios.entity.Funcionario;

public class App {

    public static void main(String[] args) throws Exception {
        
        List<Funcionario> funcionarios = new ArrayList<>();

        Funcionario f1 = new Funcionario(1L, "João Batista", 5000.0);
        Funcionario f2 = new Funcionario(2L, "Maria conceição", 4000.0);
        Funcionario f3 = new Funcionario(3L, "José Bezerra", 2500.0);

        funcionarios.add(f1);
        funcionarios.add(f2);
        funcionarios.add(f3);

        Long idParaEncontrar = 1L;

        Optional<Funcionario> funcionarioOpt = funcionarios.stream()
                                                        .filter(f -> f.getId() == idParaEncontrar)
                                                        .findFirst();
        
        if (funcionarioOpt.isEmpty()) {
            throw new Exception("Funcionário não encontrado para id #" + idParaEncontrar);
        }

        Funcionario funcionario = funcionarioOpt.get();

        System.out.println("# Antes do aumento");
        System.out.println(funcionario);

        funcionario.aumentarSalario(10);
        funcionario.setNome("Pedro");

        System.out.println("\n# Depois do aumento");

        for (Funcionario f : funcionarios) {
            System.out.println(f);
        }
    }
}
