/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pagination;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class App {
    public static void main(String[] args) {

        //List<Integer> lista = Stream.of(1,2,3,4,5,6,7,8,9,10).toList();

        List<String> lista = new ArrayList<>();
        lista.add("Maçã");
        lista.add("Banana");
        lista.add("Laranja");
        lista.add("Morango");
        lista.add("Pera");
        lista.add("Uva");
        lista.add("Abacaxi");
        lista.add("Manga");
        lista.add("Melancia");
        lista.add("Cereja");

        System.out.println("Original:");
        System.out.println(lista);
        
        Pagination<String> pag = new Pagination<>(lista);

        System.out.println("Paginação padrão:");
        System.out.println(pag.getContent());

        pag.setItemsPerPage(5);

        pag.setPage(1);
        System.out.println("Paginação 1/2");
        System.out.println(pag.getContent());

        pag.setPage(2);
        System.out.println("Paginação 2/2");
        System.out.println(pag.getContent());

        pag.setItemsPerPage(3);
        
        pag.setPage(1);
        System.out.println("Paginação 1/4");
        System.out.println(pag.getContent());

        pag.setPage(2);
        System.out.println("Paginação 2/4");
        System.out.println(pag.getContent());

        pag.setPage(3);
        System.out.println("Paginação 3/4");
        System.out.println(pag.getContent());
        System.out.println(pag.getCurrentItemsPerPage());

        pag.setPage(4);
        System.out.println("Paginação 4/4");
        System.out.println(pag.getContent());
        System.out.println(pag.getPage());
        System.out.println(pag.getCurrentItemsPerPage());

    }
}
