/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tv.app;

import tv.app.dao.UsuarioDAO;
import tv.app.entity.Usuario;
import tv.app.service.PlataformaService;
import tv.app.service.UsuarioService;

public class App {

    public static void main(String[] args) throws Exception {
        
        UsuarioService us = new UsuarioService(new UsuarioDAO());

        Usuario u1 = new Usuario("pedro.052", "112233");
        System.out.println(us.registrar(u1));

        Usuario u2 = new Usuario("pedro.053", "112233");
        System.out.println(us.registrar(u2));

        us.listar().forEach(u -> System.out.println(u.getUsername()));

        PlataformaService plataforma = new PlataformaService(new UsuarioDAO());

        // esperado falha pq não existe
        plataforma.login("pedro.053", "112234"); 
        
        // falha pq n fez pagamento
        plataforma.login("pedro.052", "112233");

        // após realizar pagamento o usuário tem acesso por 10 segundos
        plataforma.realizarPagamento(u1);

        // esperar 2 segundos e fazer login (OK)
        Thread.sleep(2000);
        plataforma.login("pedro.052", "112233");
        
        // esperar 15 segundos e fazer login (falha, tempo expirado)
        Thread.sleep(15000);
        plataforma.login("pedro.052", "112233");
    }
}
