/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package planocargocarreira;

import planocargocarreira.model.Analista;
import planocargocarreira.model.IPlanoCarreira;
import planocargocarreira.model.Servidor;

public class App {
    public static void main(String[] args) {

        IPlanoCarreira planoCarreiraAnalista = new Analista();
        
        Servidor servidor1 = new Servidor();
        servidor1.setMatricula("2023002");
        servidor1.setPlanoCarreira(planoCarreiraAnalista);

        for (int i = 0; i < 10; i++) {
            System.out.println(servidor1.getCargo());
            servidor1.promossao();
        }

        // System.out.println(servidor1.getCargo());

        // servidor1.promossao(); 

        // System.out.println(servidor1.getCargo());

        // servidor1.promossao(); 

        // System.out.println(servidor1.getCargo());

        // servidor1.progressao();
        
        // System.out.println(servidor1.getCargo());

        // servidor1.progressao();

        // System.out.println(servidor1.getCargo());

        // servidor1.progressao();

        // System.out.println(servidor1.getCargo());

        // servidor1.progressao();

        // System.out.println(servidor1.getCargo());

        // servidor1.promossao();

        // System.out.println(servidor1.getCargo());
    }
}
