/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prova.pratica;

import org.junit.Test;

import prova.pratica.numeroMaximo.NumeroMaximo;
import prova.pratica.palindromo.Palindromo;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void numero_maximo() {

        NumeroMaximo nm = new NumeroMaximo();

        int[] lista = {1,2,3,4,5};

        int nmax = nm.numeroMaximo(lista);

        assertEquals(5, nmax);
        assertNotEquals(4, nmax);
    }

    @Test public void eh_palindromo() {

        Palindromo pl = new Palindromo();

        assertEquals(true, pl.ehPalindromo("Amor a Roma"));
        assertEquals(true, pl.ehPalindromo("O lobo ama o bolo"));
        assertEquals(true, pl.ehPalindromo("aibofobia"));
        assertEquals(true, pl.ehPalindromo("sopapos"));
        assertEquals(false, pl.ehPalindromo("dasdjiadjiajds"));
    } 
}