/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdbc.example;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

public class App {
    
    private final String url = "jdbc:postgresql://localhost:5432/nestjsapp";
    private final String user = "peter";
    private final String password = "28120134";

    /**
     * Connect to the PostgreSQL database
     *
     * @return a Connection object
     */
    public Connection connect() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the PostgreSQL server successfully.");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        return conn;
    }

    public static void main(String[] args) {
        App app = new App();
        Connection conn = app.connect();
        
        try(Statement stmt = conn.createStatement()) {
            ResultSet resultSet = stmt.executeQuery("select * from clientes;");

            while(resultSet.next()) {
                int id = resultSet.getInt("id");
                String nome = resultSet.getString("nome");
                System.out.printf("%d - %s%n", id, nome);
            }
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
