/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.calc;

public class App {
    public static void main(String[] args) {
        // SetBits sb = new SetBits();

        // //System.out.println(sb.eliminateUnsetBits("11010101010101"));
        // //System.out.println(sb.eliminateUnsetBits("111"));

        // ArrayPrinter ap = new ArrayPrinter();

        // Integer[] array = new Integer[] { 2, 4, 5, 2 };
        // System.out.println(ap.printArray(array));

        //System.out.println(Divisible.isDivisible(12,2,3,6));

        //System.out.println(RgbToHex.convert(255));
        System.out.println(RgbToHex.rgb(148, 0, 211));
    }
}
