/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package random;

import java.util.List;
import java.util.Random;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;

public class App {
    public static void main(String[] args) {
        // Random random = new Random();

        // System.out.println(random.nextInt());

        // System.out.println(random.nextDouble());

        // System.out.println(random.nextBoolean());

        // System.out.println(random.nextInt(-10,10));

        // // intStream
        // //IntStream.of(1, 2, 3).forEach(System.out::print);

        // //DoubleStream.of(1.5, 2.7, -10.2).forEach(System.out::print);

        // IntStream.of(3, 1, 6, 2, 10, 0, 1).sorted().forEach(x -> System.out.printf("%d ", x));

        List<String> res = QueenOnChessboard.availableMoves("A1");

        for (String str : res) {
            System.out.println(str);
        }
    }
}
