/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crud.sem.database;

import java.util.List;

import crud.sem.database.dao.ProdutoDBDao;
import crud.sem.database.dao.ProdutoDao;
import crud.sem.database.entity.Produto;
import crud.sem.database.service.ProdutoService;

public class App {

    public static void main(String[] args) throws Exception {

        ProdutoService produtoService = new ProdutoService(new ProdutoDBDao());
        
        Produto produto1 = new Produto(1L, "Smartphone Samsung A31", 2500.0, 150);
        Produto produto2 = new Produto(2L, "Notebook Dell", 4200.0, 100);

        produtoService.cadastrar(produto1);
        produtoService.cadastrar(produto2);

        System.out.println("\n------ LISTAR ------");
        for (Produto produto : produtoService.listar()) {
            System.out.println(produto);
        }
        
        System.out.println("\n------- BUSCAR ------");
        Produto produtoBuscado = produtoService.buscar(2L);
        System.out.println(produtoBuscado);
        
        System.out.println("\n------- ATUALIZAR -------");
        Produto produtoNovo = new Produto("Notebook Dell", 4200.0, 50);
        Produto produtoAtualizado = produtoService.atualizar(produtoNovo, 2L);
        for (Produto produto : produtoService.listar()) {
            System.out.println(produto);
        }

        System.out.println("\n------- DELETE -------");
        produtoService.remover(1L);
        for (Produto produto : produtoService.listar()) {
            System.out.println(produto);
        }
    }
}
