/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package item.shop;

public class App {

    public static void main(String[] args) throws Exception {
        
        Item faca = new Item("faca simpes", 10, 250);

        Item espadaLonga = new Item("espada longa", 25, 580);
        espadaLonga.addChildrenItem(faca);
        espadaLonga.addChildrenItem(faca);

        Item claymore = new Item("claymore", 70, 1800);
        claymore.addChildrenItem(faca);
        claymore.addChildrenItem(espadaLonga);

        Player eu = new Player(5000);
        
        try {
            eu.buyItem(faca);
            eu.status();
            eu.buyItem(faca);
            eu.status();
            // eu.buyItem(espadaLonga);
            // eu.status();
            eu.buyItem(faca);
            eu.status();
            eu.buyItem(claymore);
            eu.status();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }


    /* 
        3
        /\
       2  1
      /\
     1  1
    */
    /*
    1 1 + c(2) = 2
    2 1 + c(3) = 3
    1 1 1 + c(2) = 1 2
    2 1 2 + c(3) = 2 3
    2 1 + c(1) = 2 1 1

    para o item I
    se não tem filho
        adiciono o item I
    senão
        para filho de item I
            se tem filho
                remove filho
        adiciona o item I
    */


            // if (this.items.containsAll(item.getChildrenItems())) {
            //     this.items.removeAll(item.getChildrenItems());
            //     this.items.add(item);
            //     System.out.println("aqui 2");
            //     return;
            // } else {
            //     this.items.add(item);
            //     System.out.println("aqui 3");
            //     return;
            // }
}
